<?php
// Moodle Configuration File
// This file is automatically generated during Moodle installation
// Do not edit this file manually unless you know what you're doing

$CFG = new stdClass();

// Database configuration
$CFG->dbtype    = 'pgsql';        // postgresql, mariadb, mysql, mssql, oracle
$CFG->dblibrary = 'native';     // 'native' only at the moment
$CFG->dbhost    = 'postgres';     // database server hostname
$CFG->dbname    = 'moodle';       // database name
$CFG->dbuser    = trim(file_get_contents('/run/secrets/postgres_user'));      // database username
$CFG->dbpass    = trim(file_get_contents('/run/secrets/postgres_password')); // database password
$CFG->prefix     = 'mdl_';         // Prefix to use for all table names
$CFG->dboptions = array(
    'dbpersist' => false,
    'dbsocket'  => false,
    'dbport' => '5432',
);

// Site configuration
$CFG->wwwroot   = 'https://localhost';
$CFG->dataroot  = '/var/www/moodledata'; // Moodle data directory
$CFG->admin     = 'admin';

// Security settings
$CFG->passwordsaltmain = 'CHANGE_ME_IN_PRODUCTION_SALT_2024';
$CFG->siteidentifier = 'moodle_localhost_2024';

// Performance settings
$CFG->cachetype = 'redis';
$CFG->redis_server_host = 'redis';
$CFG->redis_server_port = 6379;
$CFG->redis_server_db = 0;
$CFG->redis_server_auth = trim(file_get_contents('/run/secrets/redis_password'));
$CFG->redis_server_timeout = 5;

// Session configuration
$CFG->session_handler = 'redis';
$CFG->session_redis_host = 'redis';
$CFG->session_redis_port = 6379;
$CFG->session_redis_db = 1;
$CFG->session_redis_auth = trim(file_get_contents('/run/secrets/redis_password'));
$CFG->session_redis_timeout = 5;
$CFG->session_timeout = 7200;

// Debug settings - set to 0 for production
$CFG->debug = 0;
$CFG->debugdisplay = 0;
$CFG->debugstringid = 0;
$CFG->perfdebug = 0;
$CFG->perfdebugdata = NULL;
$CFG->debugdeveloper = false;
$CFG->debugpageinfo = false;
$CFG->debugsmtp = false;
$CFG->debugmailsmtp = false;

// Directory and file settings
$CFG->umaskpermissions = 027;
$CFG->runclionbackup = true;

// Language and locale
$CFG->lang = 'en';
$CFG->langmenu = true;
$CFG->langcache = true;
$CFG->locale = 'en_AU.UTF-8';

// Email settings
$CFG->smtphosts = '';
$CFG->smtpuser = '';
$CFG->smtppass = '';
$CFG->smtpsecure = '';
$CFG->noreplyaddress = 'noreply@localhost';

// Security headers
$CFG->allowframembedding = false;
$CFG->allowobjectembed = true;
$CFG->allowthirdpartycookies = 0;
$CFG->loginhttps = true;

// Performance optimization
$CFG->themerev = 1;
$CFG->jsrev = 1;
$CFG->cssrev = 1;
$CFG->cachejs = true;
$CFG->cachecss = true;

// Required for Moodle 4.x
$CFG->directorypermissions = 02777;
$CFG->cachedir = '/var/www/moodledata/cache';

require_once(__DIR__ . '/lib/setup.php');
