# Common PHP-FPM parameters
fastcgi_index index.php;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
fastcgi_param PATH_INFO $fastcgi_path_info;
include fastcgi_params;

# Moodle-specific settings
fastcgi_read_timeout 600s;
fastcgi_send_timeout 600s;
fastcgi_param PHP_VALUE "upload_max_filesize=100M \n post_max_size=100M \n max_execution_time=300 \n max_input_time=300 \n memory_limit=1G";
