apiVersion: v1
kind: Secret
metadata:
  name: moodle-secrets
  namespace: moodle
type: Opaque
stringData:
  db-password: "5uR:rjF[}!8);7yD+FZpI7QlfAV^bqjH"          # secure generated password
  admin-password: "e.@&boM=On--cE%G"                         # secure generated password
  # If you need a custom secret key for Moodle, generate one (e.g., 32 chars)
  moodle-secret-key: "5uR:rjF[}!8);7yD+FZpI7QlfAV^bqjH"    # 32 character secure key